# Generated by Django 2.2.8 on 2019-12-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Album'),
        ),
    ]
